### ISSUE TITLE
Implement the model

### ISSUE THREAD

**Issue by Ash12H** [Ash12H/seapodym-lmtl-python#6]
# ToDo

| Fonction                           | Priority |
|------------------------------------|----------------------|
| init_client_locally                | ✩                    |
| close_client_locally               | ✩                    |
| parse_configuration_file          | ✩✩                  |
| save_configuration_locally         | ✩✩                  |
| save_outputs_locally               | ✩✩                  |
| model_configuration                | ✩✩                  |
| biomass.process                    | ✩✩✩                |
| production.process                 | ✩✩✩✩              |
| pre_production.process             | ✩✩✩✩✩            |

## Done

- [x] init_client_locally
- [x] close_client_locally
- [ ] #15
- [ ] #16
- [ ] #17
- [x] model_configuration
- [x] biomass.process
- [x] production.process
- [x] pre_production.process
